### ISSUE TITLE
Version 0.0.9 to 0.0.10

### ISSUE THREAD

**Issue by lengletremy** [pietrocinaglia/laraupdater#2]
Hello,
First of all thank you for this extension. I have just encountered a small problem, in fact when the current version is 0.0.9 and I want to upgrade to 0.0.10, the system does not detect an update.

**Comment by pietrocinaglia** [comment]
Hi, I think that the issue is related to the format used for the version... the script checks the update's version using the following code:
`if ( $lastVersionInfo['version'] > $this->getCurrentVersion() )`
...so the format must be a number, for example: 0.9 and 0.10
Try to change 0.09 in 0.9, and 0.010 in 0.10
Keep me updated :)

**Comment by fisharebest** [comment]
Use [version_compare()](http://php.net/version_compare) ??

**Comment by pietrocinaglia** [comment]
Great idea... thanks a lot !!! Now, check() function is improved using version_compare ;)
